# Generated by Django 6.0.4 on 2026-05-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
