# Generated by Django 6.0.4 on 2026-05-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
