# Generated by Django 6.0.4 on 2026-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_hotel_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
    ]
