# Generated by Django 6.0.4 on 2026-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_hotel_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Otel Adı'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gecelik Fiyat'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.IntegerField(verbose_name='Yıldız Sayısı'),
        ),
    ]
