# Generated by Django 6.0.4 on 2026-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_hotel_city_alter_hotel_name_alter_hotel_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Otel', 'verbose_name_plural': 'Oteller'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.FloatField(default=4.5, verbose_name='Yıldız Puanı'),
        ),
    ]
